sudo: false
language: node_js

node_js:
  - "14.4.0"

script :
  - npm run build
  - mv dist/* .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  verbose: true
  deployment_file: true
  on:
    branch: master
